// Re-export Material UI components
export {
  // Layout
  Box,
  Container,
  Grid,
  Stack,
  // Inputs
  Button,
  TextField,
  Select,
  MenuItem,
  Checkbox,
  Radio,
  RadioGroup,
  FormControl,
  FormControlLabel,
  FormLabel,
  Switch,
  Slider,
  Autocomplete,
  // Data Display
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  TablePagination,
  Typography,
  Divider,
  Chip,
  Avatar,
  Badge,
  List,
  ListItem,
  ListItemText,
  ListItemIcon,
  ListItemButton,
  Tooltip,
  // Feedback
  Alert,
  AlertTitle,
  CircularProgress,
  LinearProgress,
  Skeleton,
  Dialog,
  DialogActions,
  DialogContent,
  DialogContentText,
  DialogTitle,
  Snackbar,
  Backdrop,
  // Navigation
  Drawer,
  AppBar,
  Toolbar,
  Tabs,
  Tab,
  Menu,
  Breadcrumbs,
  Link,
  Stepper,
  Step,
  StepLabel,
  // Surfaces
  Paper,
  Card,
  CardContent,
  CardActions,
  CardHeader,
  CardMedia,
  Accordion,
  AccordionSummary,
  AccordionDetails,
  // Utils
  ClickAwayListener,
  Portal,
  Popover,
  Popper,
} from '@mui/material';

// Export Material UI Icons
export {
  Dashboard as DashboardIcon,
  ShoppingCart as ShoppingCartIcon,
  People as PeopleIcon,
  BarChart as BarChartIcon,
  Layers as LayersIcon,
  AccountCircle,
  Login,
  Logout,
  CheckCircle,
  Info,
  Warning,
} from '@mui/icons-material';

// Export types
export type {
  ButtonProps,
  TextFieldProps,
  SelectProps,
  CheckboxProps,
  RadioProps,
  SwitchProps,
  SliderProps,
  AutocompleteProps,
  TableProps,
  TypographyProps,
  AlertProps,
  CircularProgressProps,
  LinearProgressProps,
  SkeletonProps,
  DialogProps,
  SnackbarProps,
  DrawerProps,
  AppBarProps,
  TabsProps,
  TabProps,
  MenuProps,
  PaperProps,
  CardProps,
  AccordionProps,
  BoxProps,
  ContainerProps,
  GridProps,
  StackProps,
} from '@mui/material';

// Export theme and styling utilities
export {
  createTheme,
  ThemeProvider,
  styled,
  useTheme,
} from '@mui/material/styles';

export type { Theme, SxProps } from '@mui/material/styles';

// Export commonly used utilities
export { useMediaQuery } from '@mui/material';
